In [2]:
kernel_name = python3;

NameError: name 'python3' is not defined

Kopiere diesen Code in die erste Zelle deines Notebooks und führe sie anschließend aus, wenn du das Notebook lokal in einem Docker Container ausführen möchtest([Anleitung](https://projectbase.medien.hs-duesseldorf.de/eild.nrw-module/lernmodul-datenanalyse#Docker-Lokal)):
```python
kernel_name = python3
```

In [25]:
import random
import time
names=["pratik","rika","papali","pupuli","puja","Rohith","priya"]
subjects=["django","flask","heroku","postgres","git"]
# num=int(input("Enter the Number of student list"))
def student_list(num):
    students=[]
    for x in range(num):
        student={"id":x,"name":random.choice(names),"subj":random.choice(subjects)}
        time.sleep(1)
        print(student)
        students.append(student)
        
    return students
t1=time.time()
for x in student_list(100):
    print(x)
t2=time.time()
# print(l1)
print(t2-t1)

{'id': 0, 'name': 'papali', 'subj': 'flask'}
{'id': 1, 'name': 'priya', 'subj': 'django'}
{'id': 2, 'name': 'papali', 'subj': 'git'}
{'id': 3, 'name': 'papali', 'subj': 'postgres'}
{'id': 4, 'name': 'priya', 'subj': 'django'}
{'id': 5, 'name': 'puja', 'subj': 'git'}
{'id': 6, 'name': 'rika', 'subj': 'heroku'}
{'id': 7, 'name': 'priya', 'subj': 'flask'}
{'id': 8, 'name': 'papali', 'subj': 'git'}
{'id': 9, 'name': 'priya', 'subj': 'heroku'}
{'id': 10, 'name': 'priya', 'subj': 'postgres'}
{'id': 11, 'name': 'priya', 'subj': 'flask'}
{'id': 12, 'name': 'pupuli', 'subj': 'django'}
{'id': 13, 'name': 'puja', 'subj': 'postgres'}
{'id': 14, 'name': 'papali', 'subj': 'heroku'}
{'id': 15, 'name': 'pratik', 'subj': 'git'}
{'id': 16, 'name': 'rika', 'subj': 'django'}
{'id': 17, 'name': 'priya', 'subj': 'flask'}
{'id': 18, 'name': 'puja', 'subj': 'django'}
{'id': 19, 'name': 'rika', 'subj': 'postgres'}
{'id': 20, 'name': 'priya', 'subj': 'flask'}
{'id': 21, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 22, 'name': 'Rohith', 'subj': 'django'}
{'id': 23, 'name': 'puja', 'subj': 'flask'}
{'id': 24, 'name': 'rika', 'subj': 'postgres'}
{'id': 25, 'name': 'priya', 'subj': 'flask'}
{'id': 26, 'name': 'rika', 'subj': 'django'}
{'id': 27, 'name': 'papali', 'subj': 'django'}
{'id': 28, 'name': 'pupuli', 'subj': 'django'}
{'id': 29, 'name': 'priya', 'subj': 'flask'}
{'id': 30, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 31, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 32, 'name': 'puja', 'subj': 'flask'}
{'id': 33, 'name': 'rika', 'subj': 'django'}
{'id': 34, 'name': 'priya', 'subj': 'postgres'}
{'id': 35, 'name': 'papali', 'subj': 'postgres'}
{'id': 36, 'name': 'priya', 'subj': 'heroku'}
{'id': 37, 'name': 'Rohith', 'subj': 'flask'}
{'id': 38, 'name': 'pratik', 'subj': 'git'}
{'id': 39, 'name': 'pratik', 'subj': 'flask'}
{'id': 40, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 41, 'name': 'pupuli', 'subj': 'postgres'}
{'id': 42, 'name': 'Rohith', 'subj': 'flask'}
{'id': 43, 'name': 'pratik', 'subj': 'flask'}
{'id': 44, 'name': 'Rohith', 'subj': 'flask'}
{'id': 45, 'name': 'pratik', 'subj': 'postgres'}
{'id': 46, 'name': 'pratik', 'subj': 'heroku'}
{'id': 47, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 48, 'name': 'puja', 'subj': 'git'}
{'id': 49, 'name': 'puja', 'subj': 'flask'}
{'id': 50, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 51, 'name': 'rika', 'subj': 'postgres'}
{'id': 52, 'name': 'pupuli', 'subj': 'git'}
{'id': 53, 'name': 'pupuli', 'subj': 'django'}
{'id': 54, 'name': 'puja', 'subj': 'flask'}
{'id': 55, 'name': 'Rohith', 'subj': 'flask'}
{'id': 56, 'name': 'puja', 'subj': 'heroku'}
{'id': 57, 'name': 'pratik', 'subj': 'flask'}
{'id': 58, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 59, 'name': 'pratik', 'subj': 'django'}
{'id': 60, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 61, 'name': 'pratik', 'subj': 'flask'}
{'id': 62, 'name': 'priya', 'subj': 'postgres'}
{'id': 63, 'name': 'papali', 'subj': 'heroku'}
{'id': 64, 'name': 'rika', 'subj': 'git'}
{'id': 65, 'name': 'puja', 'subj': 'heroku'}
{'id': 66, 'name': 'priya', 'subj': 'django'}
{'id': 67, 'name': 'rika', 'subj': 'heroku'}
{'id': 68, 'name': 'priya', 'subj': 'git'}
{'id': 69, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 70, 'name': 'priya', 'subj': 'django'}
{'id': 71, 'name': 'rika', 'subj': 'heroku'}
{'id': 72, 'name': 'rika', 'subj': 'postgres'}
{'id': 73, 'name': 'pupuli', 'subj': 'django'}
{'id': 74, 'name': 'rika', 'subj': 'heroku'}
{'id': 75, 'name': 'puja', 'subj': 'django'}
{'id': 76, 'name': 'papali', 'subj': 'flask'}
{'id': 77, 'name': 'rika', 'subj': 'flask'}
{'id': 78, 'name': 'papali', 'subj': 'git'}
{'id': 79, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 80, 'name': 'rika', 'subj': 'django'}
{'id': 81, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 82, 'name': 'puja', 'subj': 'git'}
{'id': 83, 'name': 'pupuli', 'subj': 'django'}
{'id': 84, 'name': 'puja', 'subj': 'postgres'}
{'id': 85, 'name': 'puja', 'subj': 'postgres'}
{'id': 86, 'name': 'rika', 'subj': 'heroku'}
{'id': 87, 'name': 'papali', 'subj': 'git'}
{'id': 88, 'name': 'rika', 'subj': 'django'}
{'id': 89, 'name': 'pupuli', 'subj': 'postgres'}
{'id': 90, 'name': 'pratik', 'subj': 'flask'}
{'id': 91, 'name': 'pratik', 'subj': 'git'}
{'id': 92, 'name': 'priya', 'subj': 'postgres'}
{'id': 93, 'name': 'Rohith', 'subj': 'flask'}
{'id': 94, 'name': 'pratik', 'subj': 'flask'}
{'id': 95, 'name': 'rika', 'subj': 'flask'}
{'id': 96, 'name': 'pratik', 'subj': 'heroku'}
{'id': 97, 'name': 'Rohith', 'subj': 'django'}
{'id': 98, 'name': 'rika', 'subj': 'heroku'}
{'id': 99, 'name': 'rika', 'subj': 'postgres'}
{'id': 0, 'name': 'papali', 'subj': 'flask'}
{'id': 1, 'name': 'priya', 'subj': 'django'}
{'id': 2, 'name': 'papali', 'subj': 'git'}
{'id': 3, 'name': 'papali', 'subj': 'postgres'}
{'id': 4, 'name': 'priya', 'subj': 'django'}
{'id': 5, 'name': 'puja', 'subj': 'git'}
{'id': 6, 'name': 'rika', 'subj': 'heroku'}
{'id': 7, 'name': 'priya', 'subj': 'flask'}
{'id': 8, 'name': 'papali', 'subj': 'git'}
{'id': 9, 'name': 'priya', 'subj': 'heroku'}
{'id': 10, 'name': 'priya', 'subj': 'postgres'}
{'id': 11, 'name': 'priya', 'subj': 'flask'}
{'id': 12, 'name': 'pupuli', 'subj': 'django'}
{'id': 13, 'name': 'puja', 'subj': 'postgres'}
{'id': 14, 'name': 'papali', 'subj': 'heroku'}
{'id': 15, 'name': 'pratik', 'subj': 'git'}
{'id': 16, 'name': 'rika', 'subj': 'django'}
{'id': 17, 'name': 'priya', 'subj': 'flask'}
{'id': 18, 'name': 'puja', 'subj': 'django'}
{'id': 19, 'name': 'rika', 'subj': 'postgres'}
{'id': 20, 'name': 'priya', 'subj': 'flask'}
{'id': 21, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 22, 'name': 'Rohith', 'subj': 'django'}
{'id': 23, 'name': 'puja', 'subj': 'flask'}
{'id': 24, 'name': 'rika', 'subj': 'postgres'}
{'id': 25, 'name': 'priya', 'subj': 'flask'}
{'id': 26, 'name': 'rika', 'subj': 'django'}
{'id': 27, 'name': 'papali', 'subj': 'django'}
{'id': 28, 'name': 'pupuli', 'subj': 'django'}
{'id': 29, 'name': 'priya', 'subj': 'flask'}
{'id': 30, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 31, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 32, 'name': 'puja', 'subj': 'flask'}
{'id': 33, 'name': 'rika', 'subj': 'django'}
{'id': 34, 'name': 'priya', 'subj': 'postgres'}
{'id': 35, 'name': 'papali', 'subj': 'postgres'}
{'id': 36, 'name': 'priya', 'subj': 'heroku'}
{'id': 37, 'name': 'Rohith', 'subj': 'flask'}
{'id': 38, 'name': 'pratik', 'subj': 'git'}
{'id': 39, 'name': 'pratik', 'subj': 'flask'}
{'id': 40, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 41, 'name': 'pupuli', 'subj': 'postgres'}
{'id': 42, 'name': 'Rohith', 'subj': 'flask'}
{'id': 43, 'name': 'pratik', 'subj': 'flask'}
{'id': 44, 'name': 'Rohith', 'subj': 'flask'}
{'id': 45, 'name': 'pratik', 'subj': 'postgres'}
{'id': 46, 'name': 'pratik', 'subj': 'heroku'}
{'id': 47, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 48, 'name': 'puja', 'subj': 'git'}
{'id': 49, 'name': 'puja', 'subj': 'flask'}
{'id': 50, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 51, 'name': 'rika', 'subj': 'postgres'}
{'id': 52, 'name': 'pupuli', 'subj': 'git'}
{'id': 53, 'name': 'pupuli', 'subj': 'django'}
{'id': 54, 'name': 'puja', 'subj': 'flask'}
{'id': 55, 'name': 'Rohith', 'subj': 'flask'}
{'id': 56, 'name': 'puja', 'subj': 'heroku'}
{'id': 57, 'name': 'pratik', 'subj': 'flask'}
{'id': 58, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 59, 'name': 'pratik', 'subj': 'django'}
{'id': 60, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 61, 'name': 'pratik', 'subj': 'flask'}
{'id': 62, 'name': 'priya', 'subj': 'postgres'}
{'id': 63, 'name': 'papali', 'subj': 'heroku'}
{'id': 64, 'name': 'rika', 'subj': 'git'}
{'id': 65, 'name': 'puja', 'subj': 'heroku'}
{'id': 66, 'name': 'priya', 'subj': 'django'}
{'id': 67, 'name': 'rika', 'subj': 'heroku'}
{'id': 68, 'name': 'priya', 'subj': 'git'}
{'id': 69, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 70, 'name': 'priya', 'subj': 'django'}
{'id': 71, 'name': 'rika', 'subj': 'heroku'}
{'id': 72, 'name': 'rika', 'subj': 'postgres'}
{'id': 73, 'name': 'pupuli', 'subj': 'django'}
{'id': 74, 'name': 'rika', 'subj': 'heroku'}
{'id': 75, 'name': 'puja', 'subj': 'django'}
{'id': 76, 'name': 'papali', 'subj': 'flask'}
{'id': 77, 'name': 'rika', 'subj': 'flask'}
{'id': 78, 'name': 'papali', 'subj': 'git'}
{'id': 79, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 80, 'name': 'rika', 'subj': 'django'}
{'id': 81, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 82, 'name': 'puja', 'subj': 'git'}
{'id': 83, 'name': 'pupuli', 'subj': 'django'}
{'id': 84, 'name': 'puja', 'subj': 'postgres'}
{'id': 85, 'name': 'puja', 'subj': 'postgres'}
{'id': 86, 'name': 'rika', 'subj': 'heroku'}
{'id': 87, 'name': 'papali', 'subj': 'git'}
{'id': 88, 'name': 'rika', 'subj': 'django'}
{'id': 89, 'name': 'pupuli', 'subj': 'postgres'}
{'id': 90, 'name': 'pratik', 'subj': 'flask'}
{'id': 91, 'name': 'pratik', 'subj': 'git'}
{'id': 92, 'name': 'priya', 'subj': 'postgres'}
{'id': 93, 'name': 'Rohith', 'subj': 'flask'}
{'id': 94, 'name': 'pratik', 'subj': 'flask'}
{'id': 95, 'name': 'rika', 'subj': 'flask'}
{'id': 96, 'name': 'pratik', 'subj': 'heroku'}
{'id': 97, 'name': 'Rohith', 'subj': 'django'}
{'id': 98, 'name': 'rika', 'subj': 'heroku'}
{'id': 99, 'name': 'rika', 'subj': 'postgres'}
100.04838633537292

In [22]:
import random
import time
names=["pratik","rika","papali","pupuli","puja","Rohith","priya"]
subjects=["django","flask","heroku","postgres","git"]
# num=int(input("Enter the Number of student list"))
def student_list(num):
#     students=[]
    for x in range(num):
        student={"id":x,"name":random.choice(names),"subj":random.choice(subjects)}
        time.sleep(1)
        yield student
#         time.sleep(1)
    return student

g1=student_list(100)
t1=time.time()
for x in g1:
    print(x)
t2=time.time()        
print(g1)
print(t2-t1)

{'id': 0, 'name': 'pupuli', 'subj': 'git'}
{'id': 1, 'name': 'pratik', 'subj': 'django'}
{'id': 2, 'name': 'pupuli', 'subj': 'git'}
{'id': 3, 'name': 'papali', 'subj': 'heroku'}
{'id': 4, 'name': 'puja', 'subj': 'django'}
{'id': 5, 'name': 'pratik', 'subj': 'postgres'}
{'id': 6, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 7, 'name': 'rika', 'subj': 'flask'}
{'id': 8, 'name': 'rika', 'subj': 'django'}
{'id': 9, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 10, 'name': 'papali', 'subj': 'postgres'}
{'id': 11, 'name': 'papali', 'subj': 'postgres'}
{'id': 12, 'name': 'pratik', 'subj': 'heroku'}
{'id': 13, 'name': 'puja', 'subj': 'django'}
{'id': 14, 'name': 'papali', 'subj': 'flask'}
{'id': 15, 'name': 'puja', 'subj': 'git'}
{'id': 16, 'name': 'pupuli', 'subj': 'postgres'}
{'id': 17, 'name': 'rika', 'subj': 'django'}
{'id': 18, 'name': 'puja', 'subj': 'flask'}
{'id': 19, 'name': 'rika', 'subj': 'postgres'}
{'id': 20, 'name': 'pratik', 'subj': 'git'}
{'id': 21, 'name': 'priya', 'subj': 'django'}
{'id': 22, 'name': 'Rohith', 'subj': 'git'}
{'id': 23, 'name': 'priya', 'subj': 'django'}
{'id': 24, 'name': 'papali', 'subj': 'postgres'}
{'id': 25, 'name': 'Rohith', 'subj': 'heroku'}
{'id': 26, 'name': 'rika', 'subj': 'postgres'}
{'id': 27, 'name': 'priya', 'subj': 'postgres'}
{'id': 28, 'name': 'rika', 'subj': 'postgres'}
{'id': 29, 'name': 'pratik', 'subj': 'heroku'}
{'id': 30, 'name': 'pupuli', 'subj': 'postgres'}
{'id': 31, 'name': 'pratik', 'subj': 'django'}
{'id': 32, 'name': 'rika', 'subj': 'django'}
{'id': 33, 'name': 'puja', 'subj': 'flask'}
{'id': 34, 'name': 'pupuli', 'subj': 'postgres'}
{'id': 35, 'name': 'rika', 'subj': 'postgres'}
{'id': 36, 'name': 'rika', 'subj': 'git'}
{'id': 37, 'name': 'papali', 'subj': 'git'}
{'id': 38, 'name': 'rika', 'subj': 'git'}
{'id': 39, 'name': 'pupuli', 'subj': 'django'}
{'id': 40, 'name': 'pratik', 'subj': 'heroku'}
{'id': 41, 'name': 'rika', 'subj': 'flask'}
{'id': 42, 'name': 'puja', 'subj': 'flask'}
{'id': 43, 'name': 'papali', 'subj': 'django'}
{'id': 44, 'name': 'pupuli', 'subj': 'django'}
{'id': 45, 'name': 'priya', 'subj': 'heroku'}
{'id': 46, 'name': 'priya', 'subj': 'git'}
{'id': 47, 'name': 'Rohith', 'subj': 'django'}
{'id': 48, 'name': 'puja', 'subj': 'flask'}
{'id': 49, 'name': 'pratik', 'subj': 'flask'}
{'id': 50, 'name': 'Rohith', 'subj': 'django'}
{'id': 51, 'name': 'priya', 'subj': 'heroku'}
{'id': 52, 'name': 'pupuli', 'subj': 'postgres'}
{'id': 53, 'name': 'papali', 'subj': 'django'}
{'id': 54, 'name': 'pratik', 'subj': 'flask'}
{'id': 55, 'name': 'puja', 'subj': 'postgres'}
{'id': 56, 'name': 'rika', 'subj': 'django'}
{'id': 57, 'name': 'Rohith', 'subj': 'git'}
{'id': 58, 'name': 'pratik', 'subj': 'flask'}
{'id': 59, 'name': 'pupuli', 'subj': 'git'}
{'id': 60, 'name': 'pupuli', 'subj': 'flask'}
{'id': 61, 'name': 'rika', 'subj': 'postgres'}
{'id': 62, 'name': 'pupuli', 'subj': 'flask'}
{'id': 63, 'name': 'puja', 'subj': 'heroku'}
{'id': 64, 'name': 'papali', 'subj': 'flask'}
{'id': 65, 'name': 'pratik', 'subj': 'heroku'}
{'id': 66, 'name': 'priya', 'subj': 'flask'}
{'id': 67, 'name': 'rika', 'subj': 'heroku'}
{'id': 68, 'name': 'pupuli', 'subj': 'flask'}
{'id': 69, 'name': 'pratik', 'subj': 'heroku'}
{'id': 70, 'name': 'rika', 'subj': 'flask'}
{'id': 71, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 72, 'name': 'papali', 'subj': 'heroku'}
{'id': 73, 'name': 'papali', 'subj': 'flask'}
{'id': 74, 'name': 'Rohith', 'subj': 'flask'}
{'id': 75, 'name': 'pratik', 'subj': 'django'}
{'id': 76, 'name': 'rika', 'subj': 'django'}
{'id': 77, 'name': 'pupuli', 'subj': 'flask'}
{'id': 78, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 79, 'name': 'priya', 'subj': 'flask'}
{'id': 80, 'name': 'priya', 'subj': 'flask'}
{'id': 81, 'name': 'priya', 'subj': 'git'}
{'id': 82, 'name': 'priya', 'subj': 'heroku'}
{'id': 83, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 84, 'name': 'rika', 'subj': 'postgres'}
{'id': 85, 'name': 'pratik', 'subj': 'flask'}
{'id': 86, 'name': 'rika', 'subj': 'heroku'}
{'id': 87, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 88, 'name': 'priya', 'subj': 'django'}
{'id': 89, 'name': 'Rohith', 'subj': 'django'}
{'id': 90, 'name': 'pupuli', 'subj': 'flask'}
{'id': 91, 'name': 'priya', 'subj': 'git'}
{'id': 92, 'name': 'pratik', 'subj': 'postgres'}
{'id': 93, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 94, 'name': 'pupuli', 'subj': 'heroku'}
{'id': 95, 'name': 'Rohith', 'subj': 'postgres'}
{'id': 96, 'name': 'pupuli', 'subj': 'flask'}
{'id': 97, 'name': 'puja', 'subj': 'postgres'}
{'id': 98, 'name': 'puja', 'subj': 'django'}
{'id': 99, 'name': 'priya', 'subj': 'flask'}
<generator object student_list at 0x071C04C0>
100.0420982837677

In [30]:
#here we want to checking how to convert the generator object to list
#there are 2 ways are there
#1st way:-
def natural_generator(n):
    i=1
    while i<=n:
        yield i
        i+=1
        n-=1
# it=natural_generator(10)
# print(it)
# l1=list(it)
# print(l1)

#2nd way:-
it=natural_generator(10)
l2=[]
while True:
    try:
        l2.append(next(it))
    except StopIteration:
        break
print(l2)

[1, 2, 3, 4, 5]

In [34]:
def range_gen(start,end):
    while start<=end:
        yield start
        start=start+1

my_range_it=range_gen(10,20)
while True:
    try:
        print(next(my_range_it))
    except StopIteration:
        break

10
11
12
13
14
15
16
17
18
19
20

In [ ]:
#coding_problem

class sentence(object):
    def __init__(self,string_value):
        self.string_value=string_value
    def __iter__(self):
        return self
    def __next__(self):
        self.splitter_str_list=self.string_value.split()
        split_itr=iter(self.splitter_str_list)
        while True:
            try:
                print(next(split_itr))
            except StopIteration:
                break
s=sentence("This is a Sentence")
for s1 in s:
    print(s1)

In [3]:
from ipywidgets import widgets, Button
import requests
btn = widgets.Button(description='Ergebnis absenden')

display(btn);

def submit_score(obj):
    try:
        if not endpoint or not uuid or not username:
            raise RuntimeError("Parameters missing");
        elif not lm:
            raise RuntimeError("LearningModule-Instance not as lm defined")

        score = lm.get_score();
        taskEvaluationString = lm.get_task_evaluation_string();
        response = requests.post(endpoint, data= {"uuid": uuid, "grade": score, "username": username, "details": taskEvaluationString })
        if response.status_code != 200:
            raise RuntimeError("Fehler beim Request: " + str(response.status_code))
    except RuntimeError as e:
        print(e)
    else:
        print("Durchführung erfolgreich abgegeben!")
btn.on_click(submit_score)

Button(description='Ergebnis absenden', style=ButtonStyle())